# ~/.tmuxinator/dev.yml

project_name: dev
project_root: ~/workspace
socket_name:
tabs:
  - editor:
      layout: main-vertical
      panes:
        - #empty
        - cd sahara
        - cd drupal
  - server:
      layout: even-vertical
      panes:
        - cd sahara && ruby ant.rb
        - tail -f /Applications/MAMP/logs/php_error.log
        - tail -f /Applications/MAMP/logs/apache_error.log
  - AWS: ssh dev-drupal01.aws.zappos.com
  - devjump: ssh devjump.zappos.net
